### PR TITLE
Merge new tools to main branch

### PR DESCRIPTION
**Pull request by arena-partner-mgr**
Merge new tools from Doug into main branch

### CODE REVIEW

**Comment by arena-partner-mgr** [comment]
Merged to main

**Comment by arena-partner-mgr** [comment]
Merge

**Comment by arena-partner-mgr** [comment]
Merge

**Review by JonathanCohnTW — APPROVED** [review]
Approved!

**Comment by arena-partner-mgr** [comment]
Merge

**Review by arena-partner-mgr — COMMENTED** [review]
Approved

**Pull request merged**
